name: 自动更新星标项目

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CHATGPT_API_URL: ${{ secrets.CHATGPT_API_URL }}
      CHATGPT_MODEL: ${{ secrets.CHATGPT_MODEL }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}


    steps:
      - name: ✅ Checkout 仓库
        uses: actions/checkout@v3

      - name: ✅ 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: ✅ 安装依赖
        run: pip install --no-cache-dir -r requirements.txt

      - name: ✅ 运行脚本生成 README
        run: python update_readme.py

      - name: ✅ 提交并推送更新
        run: |
          git config --global user.name ""
          git config --global user.email ""
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "自动更新星标项目列表" || echo "没有变更"
          git push origin HEAD:${{ github.ref_name }}
